services:
  - type: web
    name: lifextract-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: LifeExtract
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
